server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate      # ← 이렇게 중첩으로!
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul

